#### What is NumPy?

NumPy is short for Numerical Python. NumPy is one of the most important foundational packages for
Numerical computing in Python.
NumPy matters so much because it provides the core multidimensional array object that is necessary for
most tasks in scientific computing.

##### Uses of NumPy
- NumPy provides various math functions for calculations like addition, algebra, and data analysis.
- NumPy provides various objects representing arrays and multi-dimensional arrays which can be used to handle large data such as images, sounds, etc.
- NumPy also works with other libraries like SciPy (for scientific computing), Pandas (for data analysis), and scikit-learn (for machine learning).
- NumPy is fast and reliable, which makes it a great choice for numerical computing in Python.


In [8]:
import numpy as np

#### N-Dimensional Array

- ndarray is the main object on which the NumPy library is based on.
- ndarray stands for N-dimensional array. It is a multidimensional homogeneous array with a predetermined number of items.
- Homogeneous because all the items in it are of the same type and the same size.
- Each ndarray is associated with only one type of dtype

In [11]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
type(a)

numpy.ndarray

In [14]:
a.dtype

dtype('int32')

In [15]:
a.ndim

1

In [17]:
a.size

5

In [18]:
a.itemsize

4

- .itemsize can be used with ndarray objects to determine the size in bytes of each items in array.
- Another attribute data is the buffer containing the actual elements of the array.

In [20]:
a.data

#### ndarray shape
The Number of dimension
The number of dimensions and items in an array is defined by its shape. The shape is a tuple of N-positive integers that specifies the size for each dimension. The dimensions are defined as axes and the number of axes as rank.

In [22]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b.shape

(2, 5)

In [23]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

- You can pass a list or sequence of lists and tuples or sequence of tuple as arguments to the array() function.

In [26]:
c = np.array(((1,2),(3,4)))
c

array([[1, 2],
       [3, 4]])

In [28]:
d = np.array([(1,2,3),(3,4,5)])
d.shape

(2, 3)

In [29]:
e = np.array([1,2,3.3])
e.dtype

dtype('float64')

#### zeros & ones functions
- The zeros() function creates a full array of zeroes.
- The ones() function creates a full array of ones.

In [32]:
f = np.zeros((3,2))
f

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### arrange() function
You can use arange() function to generate NumPy arrays with numerical sequences.

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [40]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [41]:
np.arange(4,10,2)

array([4, 6, 8])

To generate two-dimensional arrays we can still continue to use the arange() function but combined with the reshape()
 function.

In [43]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
f = np.arange(1,13).reshape((3,4))
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
f.shape

(3, 4)

#### linespace() Function
Third argument, instead of specifying the distance between one element and the next, defines the number of elements into which we want the interval to be split.

In [50]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### random() Function
You can use random() function of the numpy.random module to obtain arrays that are filled with random values between 0 and 1.

In [52]:
np.random.random((3,2))

array([[0.13763501, 0.91310111],
       [0.44126374, 0.16809913],
       [0.58091483, 0.20036751]])

#### empty() Function
Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

In [54]:
np.empty((2,5))

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

#### eye() Function
Create a square N x M identity matrix
(1s on the diagonal and 0s elsewhere)

In [57]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Data Type of ndarray
The Data Type or dtype is a special object containing (Metadata & Data about Data)

In [60]:
arr1 = np.array([1,2,3], dtype=float)
arr1

array([1., 2., 3.])

In [61]:
arr2 = np.array([1.2,3,4], dtype=int)
arr2

array([1, 3, 4])

In [63]:
print(arr1.dtype,arr2.dtype, sep='\n')

float64
int32


NumPy arrays are designed to contain a wide range of data types

In [65]:
g = np.array([['a','b'],['c','d']])
g.dtype

dtype('<U1')

In [66]:
g.dtype.name

'str32'

In [67]:
arr3 = np.array([[1-5j,2,3], [4,5,6]], dtype=complex)
arr3

array([[1.-5.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

#### astype() Function
To explicitly convert an array from one dtype to another

In [72]:
arr4 = np.array([1,2,3,4,5])
arr4.dtype

dtype('int32')

In [74]:
float_arr = arr4.astype(float)
print(float_arr.dtype, '\n', float_arr)

float64 
 [1. 2. 3. 4. 5.]


### Airthmetic Operations

In [77]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr5 + 4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [79]:
arr5 - 4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [81]:
arr5 * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [82]:
arr5 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [84]:
arr5 % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [85]:
arr6 = np.arange(10)
arr6


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr5 + arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
arr5 * arr6

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [89]:
arr5 - arr6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
arr5 / arr6

C:\Users\hp\AppData\Local\Temp\ipykernel_11360\3149839863.py:1: RuntimeWarning: invalid value encountered in divide
  arr5 / arr6


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### MultiDimensional

In [93]:
arr7 = np.arange(0,9)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
c = arr7.reshape((3,3))
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Matrix Product
In NumPy the matrix product is performed using dot() function. This Operation is not element-wise.

In [99]:
np.dot(c,d)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [100]:
# Alternative
c.dot(d)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [101]:
a = np.ones(4).reshape((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [102]:
b = np.arange(3,7).reshape(2,2)
b

array([[3, 4],
       [5, 6]])

In [103]:
b.dot(a)

array([[ 7.,  7.],
       [11., 11.]])

#### Increment & Decrement


You can use operators such as += and -=

In [110]:
a

array([[1., 1.],
       [1., 1.]])

In [111]:
a +=3
a

array([[4., 4.],
       [4., 4.]])

In [113]:
d -= 1
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [114]:
d *= 3
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
d /= 2
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Universal Function (ufunc)
A Universal Function (ufunc), operates on an array in an element-by-element fashion. \
Example are sin(), log(), sqrt()

In [118]:
f = np.array((0., 30., 45., 60., 90.)) * np.pi / 180
f

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [120]:
np.sin(f)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [122]:
g = np.arange(1,5)
g

array([1, 2, 3, 4])

In [124]:
np.sqrt(g)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [126]:
# for any base
array = np.array([8, 16])  # = [2^3, 2^4]
base = 2
exponent = np.emath.logn(base, array) 
exponent

array([3., 4.])

In [127]:
g.sum()

10

In [130]:
g.min()

1

In [131]:
g.max()

4

#### Indexes and Slcies 

In [136]:
a = np.arange(4,12)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
a[4]

8

In [139]:
a[-1]

11

In [140]:
a[[1,2,4]]

array([5, 6, 8])

In [142]:
a[[-1,-3,-5]]

array([11,  9,  7])

In [143]:
a[[-1,4,5]]

array([11,  8,  9])

### Two Dimensional Array 
The two-dimensional Array, namely the matrices, are represented as rectangular arrays consists of rows and Columns. \
They are defined by two axes:
- Axis 0 is represented by the rows.
- Axis 1 is represented by the columns. \
##### array_object[row_index, col_index]


In [146]:
A = np.arange(10, 19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [148]:
A[1]

array([13, 14, 15])

In [149]:
A[1,2]

15

#### Slicing 
Using Slicing, you can extract portions of an array to generate new arrays.\
Python lists slices are copies whereas array slices are views on the original array.

In [152]:
arr7 = np.arange(7)
arr7

array([0, 1, 2, 3, 4, 5, 6])

In [153]:
arr7[5]

5

In [155]:
arr7[5:8]

array([5, 6])

#### Python Slicing VS NumPy Slicing

In [159]:
arr7

array([0, 1, 2, 3, 4, 5, 6])

In [161]:
arr_slice = arr7[5:8]
arr_slice

array([5, 6])

In [163]:
arr_slice[1] =11
arr_slice

array([ 5, 11])

In [164]:
arr7

array([ 0,  1,  2,  3,  4,  5, 11])

In [165]:
arr7[5:8].copy()

array([ 5, 11])

In [166]:
# Now in Python
c = list(range(10))
c

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [167]:
d = c[2:4]
d

[2, 3]

In [170]:
d[1]= 11
d

[2, 11]

In [171]:
c

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Skipping Items

In [174]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [175]:
a[2:5:2]

array([12, 14])

This notation [ start : stop : step ] is used in NumPy for slicing arrays.
- If the first number is missing → It starts from the beginning (index 0).
- If the second number is missing → It goes all the way to the end.
- If the third number is missing → It moves one step at a time (default step is 1).

In [178]:
a[::2]

array([10, 12, 14])

In [180]:
a[:3:]

array([10, 11, 12])

In [181]:
a[-2::]

array([14, 15])

#### Multidimensional Array

In [184]:
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [185]:
# arr3 is 2X3 array.
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
arr3[0,0]

array([1, 2, 3])

In [188]:
arr3[0,0,0]

1

#### Boolean Indexing

In [191]:
Age = np.array(range(21,27))
Age

array([21, 22, 23, 24, 25, 26])

In [192]:
bool_array = np.array([True, False, False, False, False, True])

In [194]:
Age[bool_array]

array([21, 26])

#### Reshape and Shape
We can convert a 1D array into a matrix by using reshape() function.

In [198]:
arr10 = np.random.random(12)
arr10

array([0.35803331, 0.47290421, 0.79362396, 0.78006735, 0.64129603,
       0.29190259, 0.38870005, 0.57309884, 0.13752094, 0.25685019,
       0.42701176, 0.71490128])

In [199]:
arr11 = arr10.reshape(3,4)
arr11

array([[0.35803331, 0.47290421, 0.79362396, 0.78006735],
       [0.64129603, 0.29190259, 0.38870005, 0.57309884],
       [0.13752094, 0.25685019, 0.42701176, 0.71490128]])

In [200]:
arr10.shape

(12,)

In [201]:
arr10.shape = (3,4)
arr10

array([[0.35803331, 0.47290421, 0.79362396, 0.78006735],
       [0.64129603, 0.29190259, 0.38870005, 0.57309884],
       [0.13752094, 0.25685019, 0.42701176, 0.71490128]])

#### ravel()
Convert N-D array into 1D array by using ravel() function.
Its returns the reference of original array.

In [205]:
arr2 = arr10.ravel()
arr2

array([0.35803331, 0.47290421, 0.79362396, 0.78006735, 0.64129603,
       0.29190259, 0.38870005, 0.57309884, 0.13752094, 0.25685019,
       0.42701176, 0.71490128])

In [206]:
arr2.shape

(12,)

In [207]:
arr2[1] = 1
arr2

array([0.35803331, 1.        , 0.79362396, 0.78006735, 0.64129603,
       0.29190259, 0.38870005, 0.57309884, 0.13752094, 0.25685019,
       0.42701176, 0.71490128])

In [208]:
arr10

array([[0.35803331, 1.        , 0.79362396, 0.78006735],
       [0.64129603, 0.29190259, 0.38870005, 0.57309884],
       [0.13752094, 0.25685019, 0.42701176, 0.71490128]])

#### Flatten()
Convert a nD array to 1D array.\
It returns the copy of the original array.

#### Combining Arrays
##### 1. Concatenate 

In [211]:
arr1 = np.array([[1,2],[5,6]])
print(arr1)

[[1 2]
 [5 6]]


In [265]:
arr2 = np.array([[7, 8], [3,4]])
print(arr2)

[[7 8]
 [3 4]]


In [267]:
a = np.concatenate((arr1, arr2), axis = 1)
print(a)

[[1 2 7 8]
 [5 6 3 4]]


In [269]:
a = np.concatenate((arr1, arr2), axis = 0)
print(a)

[[1 2]
 [5 6]
 [7 8]
 [3 4]]


##### 2. hstack 

In [273]:
a = np.array([[1, 2],[3,4]])
b = np.array([[5,6],[7,8]])

np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### 2. vstack 

In [277]:
a = np.array([[1, 2],[3,4]])
b = np.array([[5,6],[7,8]])

np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

##### 2. dstack 

In [283]:
a = np.array([[1, 2],[3,4]])
b = np.array([[5,6],[7,8]])

np.dstack((a,b))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

### .newaxis 
numpy.newaxis is used to increase the dimension of an existing array by one.\
particularly useful for reshaping arrays and for operations like broadcasting, where arrays with different shapes need to be aligned.

In [288]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [290]:
arr.shape

(3,)

In [294]:
colarr = arr[:,np.newaxis]
colarr

array([[1],
       [2],
       [3]])

In [296]:
colarr.shape

(3, 1)

In [298]:
rowarr = colarr[np.newaxis,:]
rowarr

array([[[1],
        [2],
        [3]]])

In [300]:
rowarr.shape

(1, 3, 1)